Use ES6 syntax.
digitalbazaar/bedrock-angular-model pull request #1
Opened 2017-05-22 20:20 UTC by mattcollier

2017-05-22 22:57 UTC, dlongley approved these changes

2017-05-23 21:45 UTC, davidlehn approved these changes

2017-05-26 20:33 UTC, dlongley requested changes

2017-05-26 20:33 UTC, dlongley commented on index.js
> +var module = angular.module('bedrock.model', []);
var => const

2017-05-26 20:33 UTC, dlongley commented on package.json
> +  "version": "2.0.1-dev",
Should we bump this to `3.0.0-dev`? Or just let magic scripts handle it?

2017-05-26 20:35 UTC, dlongley approved these changes

2017-05-26 20:37 UTC, merged